name: B4BAdvancements
main: hasjamon.b4badvancements.B4BAdvancements
api-version: 1.18
authors: [ HasJamOn, Bahm ]
depend: [Block4Block]
softdepend: [ProtocolLib, Pay4PlayersAPI]
version: 2.1
description: Advancements addon for the Block4Block plugin