name: B4BAdvancements
main: hasjamon.b4badvancements.B4BAdvancements
api-version: 1.20
authors: [ HasJamOn, Bahm ]
depend: [Block4Block]
softdepend: [ProtocolLib, Pay4PlayersAPI]
version: 2.4
description: Advancements addon for the Block4Block plugin
commands:
  givepoints:
    description: Tranfers x points to a player.
    usage: /<command> player amount
    permission: console