name: B4BAdvancements
main: hasjamon.b4badvancements.B4BAdvancements
api-version: 1.17
authors: [ HasJamOn, Bahm ]
depend: [Block4Block]
softdepend: [ProtocolLib]
version: 1.0
description: Advancements addon for the Block4Block plugin